export const MESSENGER_STRINGS = {
  SERVER_OPEN_CHAT: 'SERVER:OPEN_CHAT',
  SERVER_NEW_CHAT: 'SERVER:NEW_CHAT',
  SERVER_NEW_CHAT_MESSAGE: 'SERVER:NEW_CHAT_MESSAGE',
  SERVER_READ_CHAT_MESSAGES: 'SERVER:READ_CHAT_MESSAGES',
  SERVER_CHAT_MESSAGE_DELETED: 'SERVER:CHAT_MESSAGE_DELETED',
  // SERVER_CHAT_TYPING: 'SERVER:CHAT_TYPING',
};

export const CHAT_TYPES = {
  PERSONAL: 100,
  GROUP: 200,
  SUPPORT: 300,
};
