name: Push to Yandex Cloud Container Registry
on:
  push:
    branches: [ main ] # измените ветку по вашему выбору

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}


      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpn9ikb6hp5v19o9957
          CR_REPOSITORY: inf-frontend-dev
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG


          - name: Checkout source code
          uses: actions/checkout@v2
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Install Helm
        uses: azure/setup-helm@v1
          
      - name: Configure Git
        run: |
          git config --global user.email "savamedvedevvv@gmail.com"
          git config --global user.name "jakkaru-devops"

          - name: Clone Helm repository
            run: git clone http://jakkaru-devops:sava131097@$helm_repo/git@github.com:jakkaru-devops/inf-argocd.git
          
          - name: Update version and repository in Helm charts
            run: |
              cd $CI_PROJECT_NAME
              sed -i "s|app.version.*|app.version: \"$IMAGE_TAG\"|" values.yaml
              git add values.yaml
              git diff-index --quiet HEAD || git commit -m "CI: Update app version to $IMAGE_TAG"
              git push
