name: Push to Yandex Cloud Container Registry Frontend
env:
  SOURCE_REPO_ARGOCD: https://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@github.com/jakkaru-devops/inf-argocd
  IMAGE_TAG: ${{ github.sha }}
  CI_PROJECT_NAME: inf-argocd/HelmCharts/Development
on:
  push:
    branches: [ main ] # измените ветку по вашему выбору

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # # Runs a single command using the runners shell
      # - name: Yandex Cloud CR "Login" Action for GitHub Actions
      #   uses: yc-actions/yc-cr-login@v0.1-alpha
      #   with:
      #     yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}


      # - name: Build, tag, and push image to Yandex Cloud Container Registry
      #   env:
      #     CR_REGISTRY: crpn9ikb6hp5v19o9957
      #     CR_REPOSITORY: inf-frontend-dev
      #   run: |
      #     docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
      #     docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

        
      # - name: Set up SSH
      #   uses: webfactory/ssh-agent@v0.5.1
      #   with:
      #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      # - name: Install Helm
      #   uses: azure/setup-helm@v1

      
      - name: Configure Git
        run: |
          git config --global user.email "savamedvedevvv@gmail.com"
          git config --global user.name "jakkaru-devops"

      - name: Clone Helm repository
        run: git clone $SOURCE_REPO_ARGOCD

      - name: Export env
        run: export APP_VERSION=${{ github.sha }}

      
      - name: Update tag version for api in Helm charts values
        uses: mikefarah/yq@master
        with:
          cmd: |
            cd $CI_PROJECT_NAME
            yq -i ".app.version |=env(APP_VERSION)" values.yaml                   

      - name: Update version and repository in Helm charts
        run: |
              cd $CI_PROJECT_NAME
              git add values.yaml
              git diff-index --quiet HEAD || git commit -m " CI: Update app version to $(echo $IMAGE_TAG) "
              git push
